//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string OurPartNumber { get; set; }
        public int Status { get; set; }
        public int Manufacturer { get; set; }
        public string MfgPartNumber { get; set; }
        public string MfgBarCode2D { get; set; }
        public string Description { get; set; }
        public string Unit { get; set; }
        public int Category { get; set; }
        public string GoodsOrigin { get; set; }
        public Nullable<int> SourceOfOriginInfo { get; set; }
        public string Tariff { get; set; }
        public Nullable<float> Mass { get; set; }
        public int VendorOne { get; set; }
        public Nullable<decimal> VendorOnePrice { get; set; }
        public int VendorOneCurrency { get; set; }
        public Nullable<int> VendorTwo { get; set; }
        public Nullable<decimal> VendorTwoPrice { get; set; }
        public Nullable<int> VendorTwoCurrency { get; set; }
        public string Picture { get; set; }
        public string WebPage { get; set; }
        public string Flyer { get; set; }
        public string Instructions { get; set; }
    }
}
