//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTag
    {
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int OrderNumber { get; set; }
        public int OrderLine { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> CostUSD { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
