//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public int Id { get; set; }
        public int Status { get; set; }
        public string Name { get; set; }
        public string OurAbbreviation { get; set; }
        public string NickName { get; set; }
        public string ParentCorp { get; set; }
        public int DefaultCategory { get; set; }
        public string DefaultGoodsOrigin { get; set; }
        public Nullable<int> SourceOfOriginInfo { get; set; }
        public string WebSite { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string StateOrProvince { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string PhoneMain { get; set; }
        public string SalesContact { get; set; }
        public string SalesPhone { get; set; }
        public string SalesEmail { get; set; }
        public string AcctgContact { get; set; }
        public string AcctgPhone { get; set; }
        public string AcctgEmail { get; set; }
        public string Notes { get; set; }
    }
}
